we suggested that it makes sense to split our data into two parts training and testing, we train the model on the training data set and then check how well it behaves on the testing one.

Ultimately, we are trying to avoid the scenario where the model learns to predict the training data very well, but fails miserably when given new samples. So we know why we need to split our data.

### Train Test Split

#### Import relevant libaries



In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

#### Generate some data we are going to split

In [3]:
#result and input in an array ranging form 1-100
a = np.arange(1,101)

In [39]:
a.shape

(100,)

In [4]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [40]:
b = np.arange(501,601)
b.shape

(100,)

In [41]:
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

#### Split the data

In [ ]:
#It takes an array and splits it into two arrays.

#And easy is that let's write train test split of a 
#and run the cell exactly as we anticipated.

#In general, we would prefer storing the result in 
#dedicated variables so we can write a train comma.

train_test_split(a)

In [ ]:
#In general, we would prefer storing the result in dedicated 
#variables so we can write a train comma.

#A test equals train test split of a.

#The first array is always considered to be the training array,
#while the second the testing one, let's

a_train, a_test = train_test_split(a)

In [ ]:
a_train.shape, a_test.shape

75(training)-25(testing) is not an optimal split for my work, as I really don't like dedicating so much of my data to testing to amend this, we can use an argument called test size and set it to offload between zero and one.

Therefore, to achieve an 80 20 split, we need to simply include test size equals zero point to going through the cells below.

In [ ]:
a_train, a_test = train_test_split(a, test_size=0.2)

#### Explore the result

In [ ]:
a_train.shape, a_test.shape

I have created a 80-20 split.  80% training , 20% testing

In [ ]:
a_train

In [ ]:
a_test

Both arrays are shuffled. They are completely random


We prefer our data set to be split without being shuffled. There's an argument called Shuffle, which is set to true by default.

Changing that to false would yield a very intuitive result. The first 80 observations of A would be placed in a train while the last 20 in a test.
 

In [ ]:
a_train, a_test = train_test_split(a, test_size=0.2, shuffle=False)

In [ ]:
a_train

In [ ]:
a_test

Most of the time we prefer to shuffle the data.  This removes time, dependencies, day of the week effects and so on.  Usually these are not crucial to causal relationships we are looking for.

It can only deteriorate our models, but more on that later on. For now, let's remove the shuffle argument.Now our results are shuffled again, which you may have noticed is that each time we run the code, we get a different shuffle.

In [17]:
a_train, a_test = train_test_split(a, test_size=0.2)


In [18]:
#each time you run the code, so the data is rearranged 
a_train

array([ 25,   2,  66,  63,  51,  50,  42,  92,  46,   7,  17,  35,  31,
        47,  94,  90,  36,   1,  65,  64,  27,  62,  52,  29,  84,  60,
        70,  75,  45,  86,  80,  30,  11,  99,  24,  13,  74,  73,  96,
        69,  10,  87,   3,  15,  54,  18,  78,  97,   5,  41,  21,  72,
        85, 100,  16,  40,  71,  93,  57,  33,  12,  19,  53,  79,   8,
        83,  95,   9,   6,  89,  26,  91,  77,  23,  55,  48,  20,  81,
        32,  67])

#### So if you are working on your models at home, you'd be creating a different regression on different data each time you run the cells, training a model on different training data, which generally have little impact, but it will have one nonetheless.

For instance, your R-squared is likely to change with 1% or 2% points just because of the split.  If you are trying to improve your model with many tiny tweaks, each of which are bringing one or two percent of additional explanatory power, a different shuffle every time would prevent an objective
assessment of the changes.

In the best case scenario, you would like to have shuffled data but shuffled in the same way every time. Fortunately, Escalon has a random state argument. 
Let's see it in action. I'll add the random state argument and set it to forty two. Forty two is the conventionally used number by the community a kind of an Internet joke. If we try rerunning the code again and again, we would always get the exact same shuffled split.

In [20]:
#42 is the conventionally used number by the community a kind of an Internet joke.
a_train, a_test = train_test_split(a, test_size=0.2, random_state=42)

In [36]:
a_train.shape

(80,)

In [37]:
a_test.shape

(20,)

In [47]:


a_train, a_test  = train_test_split(a,  test_size=0.2, random_state=365)

In [48]:
a_train.shape, a_test.shape

((80,), (20,))

In [49]:
a_train

array([ 25,  32,  99,  73,  91,  66,   3,  59,  94,   1,   8,  15,  90,
        54,  31,  20,  77,  82,  30,  35,  95,  42,  38,   7,  11,  50,
        21,  48,   2,  17,  10,  58,  68,  43,  41,  16,  88,  72,  79,
       100,  80,  39,  24,  86,  22,  23,  62,  76,  18,  47,  55,  26,
        60,  19,  71,  64,  51,  63,  65,  28,  12,  78,  13,  44,  75,
        87,  40,   4,  29,  49,  37,  57,  27,  74,   6,  45,  92,  34,
        53,  83])

In [50]:
a_test

array([ 9, 69, 81, 56, 33, 93, 84, 61, 46, 89, 85, 67, 97,  5, 70, 36, 98,
       96, 14, 52])

Finally, we must note that this method has another convenience.  We can split more than one array at the same time.  Here's where our B array comes into play.  We can simply add B as an argument and include two new variables to store the returned arrays will call them B train and B test.

By exploring the shapes and the arrays themselves, we reach a consistent result, a consistently ordered sequence of the numbers from one to 100 while be from five to one to six hundred. Therefore, we can say that the number one from A matches with five A one from B, twenty five from A matches with five, twenty five from B and so on.

When we split A and B using the train test split, their elements are shuffled in the same way. Exploring a train and B train, for instance, shows us that they are indeed matching. This is extremely important for regressions because we want to certain observations inputs to match with its target even after shuffling.

In [51]:
#you can change the random state using a different number
# a and be must be the same length -- 100

#a_train, a_test  = train_test_split(a, test_size=0.2, random_state=365)
a_train, a_test, b_train, b_test  = train_test_split(a, b, test_size=0.2, random_state=365)
a_train

array([ 25,  32,  99,  73,  91,  66,   3,  59,  94,   1,   8,  15,  90,
        54,  31,  20,  77,  82,  30,  35,  95,  42,  38,   7,  11,  50,
        21,  48,   2,  17,  10,  58,  68,  43,  41,  16,  88,  72,  79,
       100,  80,  39,  24,  86,  22,  23,  62,  76,  18,  47,  55,  26,
        60,  19,  71,  64,  51,  63,  65,  28,  12,  78,  13,  44,  75,
        87,  40,   4,  29,  49,  37,  57,  27,  74,   6,  45,  92,  34,
        53,  83])

In [12]:
a_test

array([ 9, 69, 81, 56, 33, 93, 84, 61, 46, 89, 85, 67, 97,  5, 70, 36, 98,
       96, 14, 52])

#### You can split more than 1 array at the same time  
Here's where our B array comes into play.
We can simply add B as an argument and include two new variables 
to store the returned arrays will call

In [55]:
a_train.shape, a_test.shape

((80,), (20,))

In [56]:
b_train.shape, b_test.shape

((80,), (20,))

In [57]:
b_train

array([525, 532, 599, 573, 591, 566, 503, 559, 594, 501, 508, 515, 590,
       554, 531, 520, 577, 582, 530, 535, 595, 542, 538, 507, 511, 550,
       521, 548, 502, 517, 510, 558, 568, 543, 541, 516, 588, 572, 579,
       600, 580, 539, 524, 586, 522, 523, 562, 576, 518, 547, 555, 526,
       560, 519, 571, 564, 551, 563, 565, 528, 512, 578, 513, 544, 575,
       587, 540, 504, 529, 549, 537, 557, 527, 574, 506, 545, 592, 534,
       553, 583])

In [58]:
b_test

array([509, 569, 581, 556, 533, 593, 584, 561, 546, 589, 585, 567, 597,
       505, 570, 536, 598, 596, 514, 552])

By exploring the shapes and the arrays themselves, we reach a consistent result, a consistently ordered sequence of the numbers for A from 1- 100 while B from 500- 600 six hundred

Therefore, we can say that the number one from A matches with five A one from B, twenty five from

A matches with five, twenty five from B and so on.

When we split A and B using the train test split, their elements are shuffled in the same way.

Exploring a train and B train, for instance, shows us that they are indeed matching.

This is extremely important for regressions because we want to certain observations inputs to match with its target even after shuffling